accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('user/', views.user_info, name="userinfo"),
    path('user/follower/', views.follower, name="follower"),
    path('user/following/', views.following, name="following"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('join/', views.join, name="join"),
    path('delete/', views.delete, name="delete"),
    path('follow/<int:user_id>', views.follow, name="follow"),
]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.main, name="home"),
    path('/<str:sort_by>', views.main, name="home"),
    path('search/', views.search, name="search"),
    path('load_more/', views.load_more)
]

products/urls.py
from django.urls import path
from . import views

app_name="products"

urlpatterns = [
    path('post/<int:post_id>/', views.post, name="post"),
    path('wirte/', views.write, name="write"),
    path('like/', views.like, name="like"),
    path('delete/<int:post_id>',views.delete, name="delete")
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('/admin', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to="images/", blank=True)
    following_num = models.PositiveIntegerField(default=0)
    follower_num = models.PositiveIntegerField(default=0)
    
class FollowRelationship(models.Model):
    following = models.ForeignKey("UserProfile", on_delete=models.CASCADE, related_name="my_following", related_query_name="my_following")
    follower = models.ForeignKey("UserProfile", on_delete=models.CASCADE, related_name="my_follower", related_query_name="my_follower")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, get_user_model
from django.contrib.auth.models import User
from django import forms
import re

username_pattern = re.compile(r'^[가-힣\s]+$')
email_pattern = re.compile(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')

class CustomUserCreationForm(UserCreationForm):
    #username = forms.CharField(validators=[])
    class Meta:
        model = get_user_model()
        fields = [
            "email",
            "username",
            "password1",
            "password2",
        ]

    def clean_username(self):
        username=self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("해당 유저네임은 이미 존재합니다!")
        
        if not (2<=len(username)<=10):
            raise forms.ValidationError("유저네임은 2글자 이상 10글자 이하여야 합니다!")

        if not bool(username_pattern.match(username)):
            raise forms.ValidationError("유저네임은 한글로만 작성되어야 합니다!")

        return username

    def clean_email(self):
        email=self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("해당 이메일은 이미 존재합니다!")

        if not bool(email_pattern.match(email)):
            raise forms.ValidationError("이메일에 부적합한 문자가 있습니다!")

        return email

class UserUpdateForm(forms.Form):
    profile = forms.ImageField()
    username = forms.CharField()

    def clean_profile(self):
        image = self.cleaned_data.get('profile')
        if image:
            if image.size > 4*1024*1024:
                raise forms.ValidationError("Image file too large (maximum size is 4MB)")
            return image
        else:
            raise forms.ValidationError("Couldn't read uploaded image")

    def clean_username(self):
        username=self.cleaned_data.get("username")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("해당 유저네임은 이미 존재합니다!")
        
        if not (2<=len(username)<=10):
            raise forms.ValidationError("유저네임은 2글자 이상 10글자 이하여야 합니다!")

        if not bool(username_pattern.match(username)):
            raise forms.ValidationError("유저네임은 한글로만 작성되어야 합니다!")

        return username

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import F
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from .forms import CustomUserCreationForm, UserUpdateForm
from .models import UserProfile, FollowRelationship
from products.models import Posts, LikeRelationship, ViewRelationship
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
@login_required
@require_http_methods(["GET", "POST"])
def user_info(request):
    user = request.user.userprofile
    if request.method =="GET":

        users_posts = Posts.objects.filter(user_id=user)
        paginator = Paginator(users_posts, 3)
        page_mypost = request.GET.get('page_mypost', 1)
        try:
            users_posts = paginator.page(page_mypost)
        except PageNotAnInteger:
            users_posts = paginator.page(1)
        except EmptyPage:
            users_posts = paginator.page(paginator.num_pages)

        users_likes = LikeRelationship.objects.filter(user_id=user).\
                exclude(post_id__user_id=user).\
                values_list('post_id', flat=True)
        users_likes = Posts.objects.filter(id__in=users_likes)
        paginator = Paginator(users_likes, 3) 
        page_mylike = request.GET.get('page_mylike', 1)
        try:
            users_likes = paginator.page(page_mylike)
        except PageNotAnInteger:
            users_likes = paginator.page(1)
        except EmptyPage:
            users_likes = paginator.page(paginator.num_pages)

        users_views = ViewRelationship.objects.filter(user_id=user).\
                exclude(post_id__user_id=user).\
                order_by('-created_at')
        #users_views = Posts.objects.filter(id__in=users_views)

        paginator = Paginator(users_views, 3)
        page_myview = request.GET.get('page_myview', 1)
        try:
            users_views = paginator.page(page_myview)
        except PageNotAnInteger:
            users_views = paginator.page(1)
        except EmptyPage:
            users_views = paginator.page(paginator.num_pages)

        context = {
            "user":user,
            "users_posts":users_posts,
            "users_likes":users_likes,
            "users_views":users_views,
        }
        return render(request, "accounts/user_info.html", context)
    else:
        image_file = request.FILES['image']
        user.profile_image = image_file
        user.save()
        return JsonResponse({'message': '이미지', 'img_link':user.profile_image.url}, status=200)

def following(request):
    user = request.user.userprofile
    following_ids = FollowRelationship.objects.filter(follower=user).values_list('following', flat=True)
    followers = UserProfile.objects.filter(user__in=following_ids)
    context = {
        "user":user,
        "followings":followers,
    }
    return render(request, "accounts/follower.html", context)

def follower(request):
    user = request.user.userprofile
    follower_ids = FollowRelationship.objects.filter(following=user).values_list('follower', flat=True)
    followings = UserProfile.objects.filter(user__in=follower_ids)
    context = {
        "user":user,
        "followings":followings,
    }
    return render(request, "accounts/following.html", context)

@require_POST
@login_required
def follow(request, user_id):
    you_follow_me = get_object_or_404(UserProfile, user_id=user_id)
    im_following_you = request.user.userprofile
    if im_following_you.user_id != you_follow_me.user_id:
        follow, created = FollowRelationship.objects.get_or_create(follower=im_following_you, following=you_follow_me)

        if not created: # 이미 팔로우한 사용자
            follow.likes_num = F('likes_num')-1
            follow.delete()
            im_following_you.following_num = F('following_num')-1
            you_follow_me.follower_num = F('follower_num')-1
        else: # 새로 좋아요를 눌렀던 포스트
            follow.likes_num = F('likes_num')+1
            im_following_you.following_num = F('following_num')+1
            you_follow_me.follower_num = F('follower_num')+1

        im_following_you.save()
        you_follow_me.save()
        im_following_you.refresh_from_db()
        you_follow_me.refresh_from_db()
        return redirect("accounts:userinfo")
    else:
        return redirect("accounts:userinfo")

@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "GET":
        form = AuthenticationForm()
        context={
            "form":form
        }
        return render(request, "accounts/login.html", context)
    else:
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            next_url = request.GET.get("next") or "main:home"
            return redirect(next_url)
        else:
            return redirect("accounts:login")
        
@require_GET
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("main:home")

@require_http_methods(["GET", "POST"])
def join(request):
    if request.method == "GET":
        form = CustomUserCreationForm()
        context = {
            "form":form,
        }
        return render(request, "accounts/join.html", context)
    else:
        form = CustomUserCreationForm(data=request.POST)
        userprofile = UserProfile()
        if form.is_valid():
            user=form.save()
            userprofile.user = user
            userprofile.save()
            auth_login(request,user)
            return redirect("main:home")
        else:
            return redirect("accounts:join")

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
        return redirect("main:home")
    else:
        return redirect("main:home")

accounts/templates/accounts/follower.html
{% extends "base.html" %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'follower/follower.css' %}" />
{% endblock style %} {% block contents %}
<div class="my_info_div">
  <div class="my_image">
    {% if user.profile_image == "" %}
    <img id="profile_img_a" src="{% static 'post/basic_post_image.webp' %}" />
    {% else %}
    <img id="profile_img_a" src="{{ user.profile_image.url }}" />
    {% endif %}
  </div>
  <div class="my_info">
    <div class="my_name">{{ request.user.username }}</div>
    <div class="my_join_date">가입일:{{ request.user.date_joined }}</div>
    <div class="my_login_date">최근 접속일:{{ request.user.last_login }}</div>
    <div class="my_follow_info">
      <div class="my_following_num">
        <a href="{% url 'accounts:following' %}"> 팔로윙 </a>
        : {{ user.following_num }}
      </div>
      <div class="my_follower_num">
        <a href="{% url 'accounts:follower' %}"> 팔로워 </a>
        : {{ user.follower_num }}
      </div>
    </div>
  </div>
</div>
<div class="follow_info">
  <div class="title">내가 팔로우한 유저</div>
  <div class="follow_card_container">
    {% for following in followings %}
    <div class="writer_div">
      <div class="writer_info">
        <div class="writer_profile">
          {% if following.profile_image == "" %}
          <img src="{% static 'post/basic_post_image.webp' %}" />
          {% else %}
          <img src="{{ following.profile_image.url }}" />
          {% endif %}
        </div>
        <div>
          <p class="writer_name">{{ following.user.username }}</p>
          <p>팔로워: {{ following.follower_num }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock contents %}

accounts/templates/accounts/following.html
{% extends "base.html" %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'following/following.css' %}" />
{% endblock style %} {% block contents %}
<div class="my_info_div">
  <div class="my_image">
    {% if user.profile_image == "" %}
    <img id="profile_img_a" src="{% static 'post/basic_post_image.webp' %}" />
    {% else %}
    <img id="profile_img_a" src="{{ user.profile_image.url }}" />
    {% endif %}
  </div>
  <div class="my_info">
    <div class="my_name">{{ request.user.username }}</div>
    <div class="my_join_date">가입일:{{ request.user.date_joined }}</div>
    <div class="my_login_date">최근 접속일:{{ request.user.last_login }}</div>
    <div class="my_follow_info">
      <div class="my_following_num">
        <a href="{% url 'accounts:following' %}"> 팔로윙 </a>
        : {{ user.following_num }}
      </div>
      <div class="my_follower_num">
        <a href="{% url 'accounts:follower' %}"> 팔로워 </a>
        : {{ user.follower_num }}
      </div>
    </div>
  </div>
</div>
<div class="follow_info">
  <div class="title">나를 팔로우한 유저</div>
  <div class="follow_card_container">
    {% for following in followings %}
    <div class="writer_div">
      <div class="writer_info">
        <div class="writer_profile">
          {% if following.profile_image == "" %}
          <img src="{% static 'post/basic_post_image.webp' %}" />
          {% else %}
          <img src="{{ following.profile_image.url }}" />
          {% endif %}
        </div>
        <div>
          <p class="writer_name">{{ following.user.username }}</p>
          <p>팔로워: {{ following.follower_num }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock contents %}

accounts/templates/accounts/join.html
{% extends "base.html" %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'join/join.css' %}" />
{% endblock style %} {% block contents %}
<form action="{% url 'accounts:join' %}" method="POST" class="join_form">
  {% csrf_token %}
  <div class="join_form_div">
    {% for field in form %}
    <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <button type="submit" class="join_btn">회원가입</button>
  </div>
  <a class="join_to_login" href="{% url 'accounts:login' %}"
    >이미 회원이신가요?</a
  >
</form>
{% endblock contents %}

accounts/templates/accounts/login.html
{% extends "base.html" %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'login/login.css' %}" />
{% endblock style %} {% block contents %}

<form action="{% url 'accounts:login' %}" method="POST" class="login_form">
  {% csrf_token %}
  <div class="login_form_div">
    {% for field in form %}
    <p>{{ field.label_tag }} {{ field }}</p>
    {% endfor %}
    <button type="submit" class="login_btn">로그인</button>
  </div>
  <a class="login_to_join" href="{% url 'accounts:join' %}"
    >회원이 아니신가요?</a
  >
</form>

{% endblock contents %}

accounts/templates/accounts/user_info.html
{% extends "base.html" %}{% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'user_info/user_info.css' %}" />
<meta name="csrf-token" content="{{ csrf_token }}" />
{% endblock style %} {% block contents %}

<div class="my_info_div">
  <div class="my_image">
    <input type="file" id="file-input" style="display: none" />
    {% if user.profile_image == "" %}
    <button id="img_btn" type="button">
      <img id="profile_img_b" src="{% static 'post/basic_post_image.webp' %}" />
    </button>
    {% else %}
    <button id="img_btn" type="button">
      <img id="profile_img_b" src="{{ user.profile_image.url }}" />
    </button>
    {% endif %}
    <div class="overlay">이미지 수정</div>
  </div>
  <div class="my_info">
    <div class="my_name">{{ request.user.username }}</div>
    <div class="my_join_date">가입일:{{ request.user.date_joined }}</div>
    <div class="my_login_date">최근 접속일:{{ request.user.last_login }}</div>
    <div class="my_follow_info">
      <div class="my_following_num">
        <a href="{% url 'accounts:following' %}"> 팔로윙 </a>
        : {{ user.following_num }}
      </div>
      <div class="my_follower_num">
        <a href="{% url 'accounts:follower' %}"> 팔로워 </a>
        : {{ user.follower_num }}
      </div>
    </div>
  </div>
</div>
<div class="my_post_div">
  <div class="title">내가 올린 물건</div>
  <div class="card_container">
    {% if users_posts|length == 0 %}
    <span>올린 물건이 없습니다!</span>
    {% else %} {% for post in users_posts %}
    <a href="{% url 'products:post' post.id %}" id="{{ post.id }}">
      <div class="post-card">
        {% if post.image != "" %}
        <img src="{{ post.image.url }}" />
        {% else %}
        <img src="{% static 'post/basic_post_image.webp' %}" />
        {% endif %}
        <div class="product_description">
          <p class="product_title">{{ post.title }}</p>
          <p class="product_date">{{ post.updated_at }}</p>
          <p class="product_info">
            조회수: {{post.views_num}} 찜: {{ post.likes_num }}
          </p>
        </div>
      </div>
    </a>
    {% endfor %} {% endif %}
  </div>
  <div class="pagination">
    <span class="step-links">
      {% if users_posts.has_previous %}
      <a href="?page_mypost=1">&laquo; 처음으로</a>
      <a href="?page_mypost={{ users_posts.previous_page_number }}">이전</a>
      {% endif %}
      <span class="current">
        {{ users_posts.number }} / {{ users_posts.paginator.num_pages }}
      </span>
      {% if users_posts.has_next %}
      <a href="?page_mypost={{ users_posts.next_page_number }}">다음</a>
      <a href="?page_mypost={{ users_posts.paginator.num_pages }}"
        >마지막으로 &raquo;</a
      >
      {% endif %}
    </span>
  </div>
</div>
<div class="my_like_div">
  <div class="title">내가 찜한 물건</div>
  <div class="card_container">
    {% if users_likes|length == 0 %}
    <span>찜한 물건이 없습니다!</span>
    {% else %} {% for post in users_likes %}
    <a href="{% url 'products:post' post.id %}" id="{{ post.id }}">
      <div class="post-card">
        {% if post.image != "" %}
        <img src="{{ post.image.url }}" />
        {% else %}
        <img src="{% static 'post/basic_post_image.webp' %}" />
        {% endif %}
        <div class="product_description">
          <p class="product_title">{{ post.title }}</p>
          <p class="product_date">{{ post.updated_at }}</p>
          <p class="product_info">
            조회수: {{post.views_num}} 찜: {{ post.likes_num }}
          </p>
        </div>
      </div>
    </a>
    {% endfor %} {% endif %}
  </div>
  <div class="pagination">
    <span class="step-links">
      {% if users_likes.has_previous %}
      <a href="?page_mylike=1">&laquo; 처음으로</a>
      <a href="?page_mylike={{ users_likes.previous_page_number }}">이전</a>
      {% endif %}
      <span class="current">
        {{ users_likes.number }} / {{ users_likes.paginator.num_pages }}
      </span>
      {% if users_likes.has_next %}
      <a href="?page_mylike={{ users_likes.next_page_number }}">다음</a>
      <a href="?page_mylike={{ users_likes.paginator.num_pages }}">
        마지막으로 &raquo;
      </a>
      {% endif %}
    </span>
  </div>
</div>
<div class="my_view_div">
  <div class="title">최근 본 물건</div>
  <div class="card_container">
    {% if users_views|length == 0 %}
    <span>올린 물건이 없습니다!</span>
    {% else %} {% for view in users_views %}
    <a
      href="{% url 'products:post' view.post_id.id %}"
      id="{{ view.post_id.id }}"
    >
      <div class="post-card">
        {% if view.post_id.image != "" %}
        <img src="{{ view.post_id.image.url }}" />
        {% else %}
        <img src="{% static 'post/basic_post_image.webp' %}" />
        {% endif %}
        <div class="product_description">
          <p class="product_title">{{ view.post_id.title }}</p>
          <p class="product_date">{{ view.post_id.updated_at }}</p>
          <p class="product_info">
            조회수: {{view.post_id.views_num}} 찜: {{ view.post_id.likes_num }}
          </p>
        </div>
      </div>
    </a>
    {% endfor %} {% endif %}
  </div>
  <div class="pagination">
    <span class="step-links">
      {% if users_views.has_previous %}
      <a href="?page_myview=1">&laquo; 처음으로</a>
      <a href="?page_myview={{ users_views.previous_page_number }}">이전</a>
      {% endif %}
      <span class="current">
        {{ users_views.number }} / {{ users_views.paginator.num_pages }}
      </span>
      {% if users_views.has_next %}
      <a href="?page_myview={{ users_views.next_page_number }}">다음</a>
      <a href="?page_myview={{ users_views.paginator.num_pages }}"
        >마지막으로 &raquo;</a
      >
      {% endif %}
    </span>
  </div>
</div>
<div class="user_delete">
  <form
    action="{% url 'accounts:userinfo' %}"
    method="POST"
    class="user_update_form"
  >
    {% csrf_token %}
    <button type="submit">정보수정</button>
  </form>
  <form
    action="{% url 'accounts:delete' %}"
    method="POST"
    class="user_delete_form"
  >
    {% csrf_token %}
    <button type="submit">회원탈퇴</button>
  </form>
</div>
{% endblock contents %} {% block script %}
<script src="{% static 'user_info/user_info.js' %}"></script>
{% endblock script %}