accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('user/', views.user_info, name="userinfo"),
    path('user/follower/', views.follower, name="follower"),
    path('user/following/', views.following, name="following"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('join/', views.join, name="join"),
    path('delete/', views.delete, name="delete"),
    path('follow/<int:user_id>', views.follow, name="follow"),
]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.main, name="home"),
    path('/<str:sort_by>', views.main, name="home"),
    path('search/', views.search, name="search"),
    path('load_more/', views.load_more)
]

products/urls.py
from django.urls import path
from . import views

app_name="products"

urlpatterns = [
    path('post/<int:post_id>/', views.post, name="post"),
    path('wirte/', views.write, name="write"),
    path('like/', views.like, name="like"),
    path('delete/<int:post_id>',views.delete, name="delete")
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('/admin', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.
class Posts(models.Model):
    image = models.ImageField(upload_to="images/", blank=True)
    title = models.CharField(max_length=20)
    body = models.TextField(max_length=100)
    user_id = models.ForeignKey("accounts.UserProfile", on_delete=models.CASCADE)
    likes_num = models.PositiveIntegerField(default=0)
    views_num = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class LikeRelationship(models.Model):
    user_id = models.ForeignKey("accounts.UserProfile", on_delete=models.CASCADE, related_name="like_posts", related_query_name="like_posts")
    post_id = models.ForeignKey("Posts", on_delete=models.CASCADE, related_name="like_users", related_query_name="like_users")

class ViewRelationship(models.Model):
    user_id = models.ForeignKey("accounts.UserProfile", on_delete=models.CASCADE, related_name="view_posts", related_query_name="view_posts")
    post_id = models.ForeignKey("Posts", on_delete=models.CASCADE, related_name="view_users", related_query_name="view_users")
    created_at = models.DateTimeField(auto_now=True)
    
class TagRelationship(models.Model):
    tag_id = models.ForeignKey("Tags", on_delete=models.CASCADE, related_name="posts", related_query_name="posts")
    post_id = models.ForeignKey("Posts", on_delete=models.CASCADE, related_name="tags", related_query_name="tags")

class Tags(models.Model):
    name = models.CharField(max_length=8, unique=True)

products/forms.py
from django import forms
from .models import Posts

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ["image",
                "title",
                "body",]
        readonly_fields = ["user_id"]

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import JsonResponse
from .forms import PostForm
from .models import Posts, ViewRelationship, LikeRelationship, Tags, TagRelationship
from accounts.models import FollowRelationship

import json, re
pattern = re.compile(r'^[가-힣#]+$')

@require_GET
def post(request, post_id):
    post = get_object_or_404(Posts, id=post_id)
    follow_user = False
    if request.user.is_authenticated:
        view_rel, create = ViewRelationship.objects.get_or_create(user_id=request.user.userprofile, post_id=post)
        if create:
            post.views_num = F("views_num") + 1
            post.save()
            post.refresh_from_db()
        else:
            view_rel.save()
        follow_rel = FollowRelationship.objects.filter(follower=request.user.userprofile.user_id,\
                                        following=post.user_id_id )
        if follow_rel.exists():
            follow_user = True
    context={
        "tags":post.tags.all(),
        "post":post,
        "writer":post.user_id,
        "follow_user":follow_user,
    }
    return render(request, "products/post.html", context)

@require_http_methods(["GET", "POST"])
@login_required
def write(request):
    if request.method == "GET":
        form = PostForm()
        context = {
            "form":form
        }
        return render(request, "products/write.html", context)
    else:
        form = PostForm(data=request.POST, files=request.FILES)
        tags = request.POST.get("tags").replace(" ","")
        if (bool(pattern.match(tags)) or tags=="") and form.is_valid():
            post = form.save(commit=False)
            post.user_id = request.user.userprofile
            post.save()

            if tags!="":
                for tag in tags.split("#")[1:]:
                    tag_rel_ins = TagRelationship()
                    tag_ins, created = Tags.objects.get_or_create(name=tag)
                    tag_rel_ins.tag_id = tag_ins
                    tag_rel_ins.post_id = post
                    tag_rel_ins.save()
            
            return redirect("products:post", post.id)
        return redirect("products:write")

@require_POST
@login_required
def like(request):
    data = json.loads(request.body)
    user = request.user.userprofile
    post = get_object_or_404(Posts, id=data.get("post_id"))
    inst, like_created = LikeRelationship.objects.get_or_create(user_id=user,post_id=post)
    if not like_created: # 이미 좋아요를 눌렀던 포스트
        post.likes_num = F('likes_num')-1
        inst.delete()
    else: # 새로 좋아요를 눌렀던 포스트
        post.likes_num = F('likes_num')+1
    post.save()
    post.refresh_from_db()
    new_like_num = post.likes_num
    print(post)
    return JsonResponse({'new_like_num': new_like_num, 'already_like': not like_created})

@require_POST
@login_required
def delete(request, post_id):
    user = request.user.userprofile
    post = get_object_or_404(Posts,id=post_id)
    if post.user_id==user:
        post.delete()
    return redirect("main:home")

products/templates/products/post.html
{% extends "base.html" %}{% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'post/post.css' %}" />
<meta name="csrf-token" content="{{ csrf_token }}" />
{% endblock style %} {% block contents %}
<div class="image">
  {% if post.image == "" %}
  <img src="{% static 'post/basic_post_image.webp' %}" />
  {% else %}
  <img src="{{ post.image.url }}" />
  {% endif %}
</div>
<div class="writer_div">
  <div class="writer_info">
    <div class="writer_profile">
      {% if writer.profile_image == "" %}
      <img src="{% static 'post/basic_post_image.webp' %}" />
      {% else %}
      <img src="{{ writer.profile_image.url }}" />
      {% endif %}
    </div>
    <div>
      <p class="writer_name">{{ writer.user.username }}</p>
      <p>팔로워: {{ writer.follower_num }}</p>
    </div>
  </div>
  {% if request.user.is_authenticated and request.user.userprofile != post.user_id %} 
  <form action="{% url 'accounts:follow' post.user_id_id %}" method="POST" class="follow_btn">
    {% csrf_token %}
    {% if follow_user %}
    <button type="submit">언팔로우</button>
    {% else %}
    <button type="submit">팔로우</button>
    {% endif %}
  </form>
  {% endif %}
</div>
<div class="title">{{ post.title }}</div>
<div class="body">{{ post.body }}</div>
<div class="tags">
  {% for tag in tags %}
  <div class="tag_box">#{{ tag.tag_id.name }}</div>
  {% endfor %}
</div>
<div class="post_info">
  <div class="post_state">
    <div class="post_time">
      <p>{{ post.created_at }}</p>
    </div>
    <div class="post_interact">
      <p id="like_num">찜수: {{ post.likes_num }} |</p>
      <p>| 조회: {{ post.views_num }}</p>
    </div>
  </div>

  <div class="post_oper">
    {% if request.user.is_authenticated %} 
    {% if request.user.userprofile == post.user_id %}
    <form action="{% url 'products:delete' post.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="delete_btn">삭제</button>
    </form>
    {% endif %}
    <form action="">
      <button
        onclick="push_likes_btn(event)"
        type="button"
        post_id="{{ post.id }}"
        class="like_btn"
      >
        찜
      </button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock contents %} {% block script %}
<script src="{% static 'post/post.js' %}"></script>
{% endblock script %}

products/templates/products/write.html
{% extends "base.html" %}{% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'write/write.css' %}" />
<meta name="csrf-token" content="{{ csrf_token }}" />
{% endblock style %} {% block contents %}
<form action="{% url 'products:write' %}" method="POST" class="write_form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form_title"><p>이미지</p></div>
  <div class="image">{{ form.image }}</div>

  <div class="form_title"><p>제목</p></div>
  <div class="title">{{ form.title }}</div>

  <div class="form_title"><p>내용</p></div>
  <div class="body">{{ form.body }}</div>

  <div class="form_title"><p>태그</p></div>
  <div class="tags_container">
    <input class="tags" name="tags" />
  </div>
  <div class="btn_container">
    <button type="submit" class="write_btn">작성</button>
  </div>
</form>
{% endblock contents %} {% block script %}
<script src="{% static 'post/post.js' %}"></script>
{% endblock script %}